---
version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
       ports:
            - 5055:5055
       volumes:
            - /jellyseerr/config:/app/config
            - /media:/media
            - /media/movies:/media/movies
            - /media/shows:/media/shows
            - /media/music:/media/music
       restart: unless-stopped
       networks:
        torrent-network:
          ipv4_address: 172.20.10.132
networks:
  torrent-network:
    external: true
