---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /jellyfin/config:/config
      - /media/movies:/movies
      - /media/shows:/shows
      - /media/music:/music
    ports:
      - 8096:8096

    restart: unless-stopped
    networks:
      torrent-network:
        ipv4_address: 172.20.10.131
networks:
  torrent-network:
    external: true

