version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       networks:
            - torrent-network
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
       ports:
            - 5055:5055
       volumes:
            - /jellyseerr/config:/app/config
            - /media:/media
            - /media/movies:/media/movies
            - /media/shows:/media/shows
            - /media/music:/media/music
       restart: unless-stopped
