---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9880
    volumes:
      - /qbittorrent/config:/config
      - /media/movies:/movies
      - /media/shows:/shows
      - /media/incomplete:/incomplete
      - /media/torrents:/torrents
      - /local/template/iso:/images

    ports:
      - 9880:9880
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      torrent-network:
        ipv4_address: 172.20.10.130

networks:
  torrent-network:
    external: true
