---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /radarr/config:/config
      - /media/movies:/movies
      - /media/shows:/shows
      - /media/music:/music
      - /media/incomplete:/incomplete
      - /media/torrents:/torrents
      - /local/template/iso:/images
    ports:
      - 7878:7878
    restart: unless-stopped
