services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /sonarr/config:/config
      - /media/movies:/movies
      - /media/shows:/shows
      - /media/music:/music
      - /media/incomplete:/incomplete
      - /media/torrents:/torrents
      - /local/template/iso:/images
networks:
  custom:
    external:
      name: torrent-network
