---
services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /sonarr/config:/config
      - /media/movies:/movies
      - /media/shows:/shows
      - /media/music:/music
      - /media/incomplete:/incomplete
      - /media/complete:/complete
      - /media/torrents:/torrents
      - /local/template/iso:/images
      - /media:/media
    networks:
      torrent-network:
        ipv4_address: 172.20.10.133
networks:
  torrent-network:
    external: true
